---

- name: Include installation tasks
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: ["install"]
  tags: ["install"]

- name: Copy env file
  ansible.builtin.template:
    src: "nut-exporter.env.j2"
    dest: "{{ nut_exporter_env_dir }}/nut-exporter"
    owner: root
    group: nut-exporter
    mode: "0640"
  notify: Restart nut exporter

- name: Copy systemd service
  ansible.builtin.template:
    src: "nut-exporter.service.j2"
    dest: /etc/systemd/system/nut-exporter.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart nut exporter

- name: Enable and start service
  ansible.builtin.systemd:
    name: nut-exporter.service
    state: started
    enabled: true
    daemon_reload: true
